//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mortgage
    {
        public int MortgageId { get; set; }
        public string Name { get; set; }
        public string MortgageType { get; set; }
        public string InterestRepayment { get; set; }
        public Nullable<System.DateTime> EffectiveStartDate { get; set; }
        public Nullable<System.DateTime> EffectiveEndDate { get; set; }
        public Nullable<int> TermsInMonths { get; set; }
        public Nullable<decimal> CancellationFee { get; set; }
        public Nullable<decimal> EstablishmentFee { get; set; }
        public string SchemaIdentifier { get; set; }
        public string Is_Active { get; set; }
    }
}
